"/":
  controller: Users
  action: default
  connexion : false
  role : 0

"/inscription":
  controller: Users
  action: register
  connexion : false
  role : 0

"/connexion":
  controller: Users
  action: login
  connexion: false
  role: 0

"/connexionFront":
  controller: Users
  action: loginFront
  connexion: false
  role: 0

"/addArticle":
  controller: Articles
  action: addArticle

"/showArticles":
  controller: Articles
  action: showArticles

"/back_office":
  controller: Articles
  action: yourWebSite
  connexion: true
  role: 2

"/front":
  controller: Articles
  action: default
  connexion: false
  role: 0

"/singlePages":
  controller: Articles
  action: singleArticle
  connexion: false
  role: 0

"/listPages":
  controller: Articles
  action: listFrontPages
  connexion: false
  role: 0

"/showPictures":
  controller: Pictures
  action: showPictures
  connexion: true
  role: 2

"/addPictures":
  controller: Pictures
  action: addPicture
  connexion: true
  role: 2

"/customizer":
  controller: Customizer
  action: default
  connexion: true
  role: 2

"/addCategory":
  controller: Categories
  action: addCategory
  connexion: true
  role: 2

"/customizeErrorPage":
  controller: ErrorPage
  action: updateErrorPage
  connexion: true
  role: 2

"/Error":
  controller: ErrorPage
  action: showErrorPage
  connexion: false
  role: 0