"/":
  controller: Users
  action: default
  connexion : false
  role : 0

"/inscription":
  controller: Users
  action: register
  connexion : false;
  role : 0;

"/connexion":
  controller: Users
  action: login
  connexion: false
  role: 0

"/connexionFront":
  controller: Users
  action: loginFront
  connexion: false
  role: 0

"/addArticle":
  controller: Articles
  action: addArticle

"/showArticles":
  controller: Articles
  action: showArticles

"/back_office":
  controller: Articles
  action: yourWebSite
  connexion: true
  role: 3

"/front":
  controller: Articles
  action: default
  connexion: false
  role: 0

"/singlePages":
  controller: Articles
  action: singleArticle

"/listPages":
  controller: Articles
  action: listFrontPages

"/showPictures":
  controller: Pictures
  action: showPictures

"/addPictures":
  controller: Pictures
  action: addPicture

"/customizer":
  controller: Customizer
  action: default

"/addCategory":
  controller: Categories
  action: addCategory

"/customizeErrorPage":
  controller: ErrorPage
  action: updateErrorPage

"/Error":
  controller: ErrorPage
  action: showErrorPage
  connexion: false
  role: 0