"/":
  controller: Users
  action: default

"/inscription":
  controller: Users
  action: register

"/connexion":
  controller: Users
  action: login

"/mot_de_passe_oublie":
  controller: Users
  action: forgetPassword

"/back_office":
  controller: Article
  action: default

"/addPage":
  controller: Article
  action: addArticle

"/showPages":
  controller: Article
  action: showArticle

"/YourWebsite":
  controller: Article
  action: yourWebSite

"/singlePages":
  controller: Article
  action: singleFrontPages

"/listPages":
  controller: Article
  action: listFrontPages

"/showPictures":
  controller: Pictures
  action: showPictures

"/addPictures":
  controller: Pictures
  action: addPicture