"/":
  controller: Users
  action: default

"/inscription":
  controller: Users
  action: register

"/connexion":
  controller: Users
  action: login

"/mot_de_passe_oublie":
  controller: Users
  action: forgetPassword

"/back_office":
  controller: Pages
  action: default

"/addPage":
  controller: Pages
  action: addPage

"/showPages":
  controller: Pages
  action: showPages

"/YourWebsite":
  controller: Pages
  action: yourWebSite

"/singlePages":
  controller: Pages
  action: singleFrontPages

"/listPages":
  controller: Pages
  action: listFrontPages

"/showPictures":
  controller: Pictures
  action: showPictures

"/addPictures":
  controller: Pictures
  action: addPicture