"/":
  controller: Users
  action: default

"/inscription":
  controller: Users
  action: register

"/connexion":
  controller: Users
  action: login

"/addArticle":
  controller: Articles
  action: addArticle

"/showArticles":
  controller: Articles
  action: showArticles

"/back_office":
  controller: Articles
  action: yourWebSite

"/singlePages":
  controller: Articles
  action: singleArticle

"/listPages":
  controller: Articles
  action: listFrontPages

"/showPictures":
  controller: Pictures
  action: showPictures

"/addPictures":
  controller: Pictures
  action: addPicture

"/customizer":
  controller: Customizer
  action: default

"/addCategory":
  controller: Categories
  action: addCategory

"/customizeErrorPage":
  controller: ErrorPage
  action: updateErrorPage

"/Error":
  controller: ErrorPage
  action: showErrorPage